export enum FormCadastro {
    select = 'SELECT',
    recibo = "RECIBO",
    data_lan = "LANÇAMENTO",
    data_ven = "VENCIMENTO",
    tipo_doc = "TIPO DOCUMENTO",
    num_doc = "Nº DOCUMENTO",
    entrada = "ENTRADAS",
    saida = "SAÍDAS",
    cong = "CONGREGAÇÃO",
    forn = "FORNECEDOR",
    dizimista = "NOME DO DIZIMISTA",
    obs = "OBS:.",
    valor = "VALOR",
    conta = "CONTA",
    situacao = "_",
    historico = "HISTÓRICO",
    status_lanc = "SITUAÇÃO",
}
