export enum Inflows {
    ENT_0 = "-",
    ENT_1 = "ENTRADA DÍZIMO OBREIRO",    
    ENT_2 = "ENTRADA OFERTAS DE CULTOS",
    ENT_3 = "ENTRADA DÍZIMO DE CONGR.",
    ENT_4 = "ENTRADA OFERTA AVULSA",
    ENT_5 = "ENTRADA COTA DO TERRENO",
    ENT_6 = "ENTRADA OFERTA ASSISTÊNCIA SOCIAL",
    ENT_7 = "ENTRADA OFERTA ATAQUE TOTAL",
    ENT_8 = "ENTRADA OFERTA MISSINÁRIA",
    ENT_9 = "ENTRADA OFERTA EBD ",
    ENT_10 = "ENTRADA EVENTO ATAQUE TOTAL",
    ENT_11 = "SALDO MÊS ANTERIOR",
}